language: go
os:
        - osx

go:
        - 1.5
        - 1.6
        - 1.7
        - 1.8
        - tip

go_import_path: github.com/currantlabs/ble

test:
        - go vet ./...
        - go test -v ./...
        - GOOS=linux go build -v ./...
